## Problem

### we have an dataset from elyom elsabe3 journal, the articles are extracted from two sections `Sports` and `Technology`

In [1]:
import pandas as pd
df = pd.read_csv('articles.csv')
df.head(2)

,url,title,image,creator,keywords,description,article,label
0,https://www.almasryalyoum.com/news/details/137...,لاسارتي يعلن تشكيل الأهلي لمباراة الساورة | ال...,https://mediaaws.almasryalyoum.com/news/veryla...,أحمد مجدي رجب,"الأهلي, لاسارتي, شبيبة الساورة, الجزائر, دوري ...",أعلن المدير الفني الأورجوياني مارتن لاسارتي ال...,أعلن المدير الفني الأورجوياني مارتن لاسارتي ال...,8.0
1,https://www.almasryalyoum.com/news/details/137...,شوط أول سلبي بين الإسماعيلي والأفريقي التونسي ...,https://mediaaws.almasryalyoum.com/news/veryla...,إيهاب بركات,"الإسماعيلي, الأفريقي, دوري الابطال, أخبار الرياضة",انتهى الشوط الأول من مباراة الإسماعيلي والأفري...,انتهى الشوط الأول من مباراة الإسماعيلي والأفري...,8.0

## this data has been extracted from our prev web_scraping

## labels means that we have two types of article pages 

### 9--> related to technology section

### 8--> related to the sport section

In [2]:
df.label.value_counts()

9.0    1000
8.0    1000
Name: label, dtype: int64

## lets choose our columns that is improtant

In [5]:
df = df[['url', 'title', 'creator', 'keywords','article']]
df.head()

,url,title,creator,keywords,article
0,https://www.almasryalyoum.com/news/details/137...,لاسارتي يعلن تشكيل الأهلي لمباراة الساورة | ال...,أحمد مجدي رجب,"الأهلي, لاسارتي, شبيبة الساورة, الجزائر, دوري ...",أعلن المدير الفني الأورجوياني مارتن لاسارتي ال...
1,https://www.almasryalyoum.com/news/details/137...,شوط أول سلبي بين الإسماعيلي والأفريقي التونسي ...,إيهاب بركات,"الإسماعيلي, الأفريقي, دوري الابطال, أخبار الرياضة",انتهى الشوط الأول من مباراة الإسماعيلي والأفري...
2,https://www.almasryalyoum.com/news/details/137...,«زادة» يشكر رئيس المقاولون العرب على دعم الزما...,كريم أبو حسـين,"الزمالك, المقاولون, هاني زاده, الكونفيدرالية, ...",أجرى المهندس هاني زادة، عضو مجلس إدارة نادي ال...
3,https://www.almasryalyoum.com/news/details/137...,حسام عاشور: مواجهة شبيبة الساورة صعبة.. والأهل...,إيهاب بركات,"الأهلي, شبيبة الساورة, حسام عاشور, محمد يوسف, ...",أكد حسام عاشور، قائد الفريق الأول لكرة القدم ب...
4,https://www.almasryalyoum.com/news/details/137...,الملعب الفرعي لبرج العرب يستضيف تدريبات المنتخ...,إيهاب بركات,"أجيري, برج العرب, منتخب مصر, النيجر, نيجيريا, ...",قرر الجهاز الفني لمنتخب مصر الوطني الأول، بقيا...

In [3]:
df.isna().sum()

url             0
title          28
image          28
creator        28
keywords       28
description    28
article        28
label           0
dtype: int64

In [53]:
100*(28/2000)

1.4000000000000001

In [5]:
df.dropna(inplace=True)

In [6]:
df.isna().sum()

url            0
title          0
image          0
creator        0
keywords       0
description    0
article        0
label          0
dtype: int64

### lets merge the text of title, creator, keyword, article 

bcuase all the text's however the locations will takes wieghts in a matrix

In [7]:
df['text'] = df.title+" "+df.creator+" "+df.keywords+" "+df.article
df.head()

,url,title,image,creator,keywords,description,article,label,text
0,https://www.almasryalyoum.com/news/details/137...,لاسارتي يعلن تشكيل الأهلي لمباراة الساورة | ال...,https://mediaaws.almasryalyoum.com/news/veryla...,أحمد مجدي رجب,"الأهلي, لاسارتي, شبيبة الساورة, الجزائر, دوري ...",أعلن المدير الفني الأورجوياني مارتن لاسارتي ال...,أعلن المدير الفني الأورجوياني مارتن لاسارتي ال...,8.0,لاسارتي يعلن تشكيل الأهلي لمباراة الساورة | ال...
1,https://www.almasryalyoum.com/news/details/137...,شوط أول سلبي بين الإسماعيلي والأفريقي التونسي ...,https://mediaaws.almasryalyoum.com/news/veryla...,إيهاب بركات,"الإسماعيلي, الأفريقي, دوري الابطال, أخبار الرياضة",انتهى الشوط الأول من مباراة الإسماعيلي والأفري...,انتهى الشوط الأول من مباراة الإسماعيلي والأفري...,8.0,شوط أول سلبي بين الإسماعيلي والأفريقي التونسي ...
2,https://www.almasryalyoum.com/news/details/137...,«زادة» يشكر رئيس المقاولون العرب على دعم الزما...,https://mediaaws.almasryalyoum.com/news/veryla...,كريم أبو حسـين,"الزمالك, المقاولون, هاني زاده, الكونفيدرالية, ...",أجرى المهندس هاني زادة عضو محلس إدارة نادي الز...,أجرى المهندس هاني زادة، عضو مجلس إدارة نادي ال...,8.0,«زادة» يشكر رئيس المقاولون العرب على دعم الزما...
3,https://www.almasryalyoum.com/news/details/137...,حسام عاشور: مواجهة شبيبة الساورة صعبة.. والأهل...,https://mediaaws.almasryalyoum.com/news/veryla...,إيهاب بركات,"الأهلي, شبيبة الساورة, حسام عاشور, محمد يوسف, ...",أكد حسام عاشور قائد الفريق الأول لكرة القدم با...,أكد حسام عاشور، قائد الفريق الأول لكرة القدم ب...,8.0,حسام عاشور: مواجهة شبيبة الساورة صعبة.. والأهل...
4,https://www.almasryalyoum.com/news/details/137...,الملعب الفرعي لبرج العرب يستضيف تدريبات المنتخ...,https://mediaaws.almasryalyoum.com/news/veryla...,إيهاب بركات,"أجيري, برج العرب, منتخب مصر, النيجر, نيجيريا, ...",قرر الجهاز الفني لمنتخب مصر الوطني الأول، بقيا...,قرر الجهاز الفني لمنتخب مصر الوطني الأول، بقيا...,8.0,الملعب الفرعي لبرج العرب يستضيف تدريبات المنتخ...

### Qustion how do i know that the article A is close to article B as we explained prev using movies example in the slides

## using the `distance metric` we can find the common words in the articles and associate the articles to each other based on the distance between the words inside each article

## 1-convert the text's to vectors

In [8]:
import re
from sklearn.feature_extraction.text import CountVectorizer
from nltk.stem import ISRIStemmer

In [16]:
cv = CountVectorizer()
## ISRIStemmer for Arabic text
ps = ISRIStemmer()   ## arabic
#sw = open('sw.txt','r').read().split('\n')   ## arabic

def clean(text):
    text = str(text)
    # filtering out the arabic words and numbers and spaces
    text = re.sub('[^ء-ي0-9 ]+','',text).strip()  
    filtered_words = []
    for word in text.split():   ## arabic 
        #if word not in sw:
        #getting back the words into its root
        filtered_words.append(ps.stem(word))
#         print('word',word,'ps.stem(word)',ps.stem(word))
## joining back the words with each other into one article again
    return ' '.join(filtered_words)

df['clean_text'] = df.text.apply(clean)

In [22]:
x  = cv.fit_transform(df.clean_text)

In [23]:
x.shape

(1972, 14785)

In [24]:
x  = cv.fit_transform(df.clean_text).toarray()
x.shape

(1972, 14785)

In [54]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [21]:
len(cv.get_feature_names())

14785

In [20]:
cv.get_feature_names()

['00',
 '001',
 '002',
 '0062007',
 '008',
 '01',
 '0100',
 '011',
 '016',
 '02',
 '0235',
 '024',
 '02ر0',
 '03',
 '04',
 '041',
 '05',
 '0512',
 '053',
 '056',
 '06',
 '065',
 '07',
 '0749',
 '08',
 '080070080003315280133152802',
 '085',
 '10',
 '100',
 '1000',
 '10000',
 '10000مشترك',
 '100389',
 '100بالمائة',
 '100وشدد',
 '101',
 '1011',
 '1012',
 '102',
 '1020',
 '1021',
 '1022019',
 '1026',
 '103',
 '103815',
 '104',
 '1047',
 '105',
 '1050',
 '106',
 '10600',
 '10634000',
 '107',
 '108',
 '1080',
 '10892000',
 '109',
 '10901',
 '1099',
 '10وقال',
 '11',
 '110',
 '1100',
 '111',
 '1113',
 '1114',
 '112',
 '112059',
 '1125',
 '113',
 '1135',
 '114',
 '11400',
 '115',
 '1152',
 '1154',
 '1155',
 '116',
 '11684',
 '117',
 '118',
 '119',
 '1197',
 '11ساع',
 '11سجل',
 '12',
 '120',
 '1200',
 '1207',
 '1209',
 '121',
 '1210',
 '1212',
 '1214',
 '1215',
 '1218',
 '122',
 '1224',
 '123',
 '123س',
 '124',
 '124124',
 '1242',
 '125',
 '1250',
 '126',
 '127',
 '127425',
 '1276',
 '128',
 '128ويبلغ',
 '129',
 '1290',
 '1299',
 '12عام',
 '13',
 '130',
 '1306',
 '1311',
 '1316',
 '132',
 '133',
 '13328',
 '134',
 '135',
 '136',
 '1367',
 '137',
 '138',
 '1383',
 '139',
 '1396',
 '13صفر',
 '14',
 '140',
 '1400',
 '140000',
 '1415',
 '1416',
 '142',
 '1420',
 '142000',
 '14222',
 '1426',
 '143',
 '1432',
 '1434',
 '1439',
 '144',
 '1440',
 '1446',
 '1448',
 '1450',
 '1465',
 '148',
 '1480729',
 '149',
 '15',
 '150',
 '1500',
 '15036',
 '150ع',
 '151',
 '1513',
 '1514',
 '1516',
 '152',
 '15222',
 '153',
 '1530',
 '154',
 '15468',
 '155',
 '1558',
 '156',
 '157',
 '1579',
 '158',
 '159',
 '16',
 '160',
 '1600',
 '160000',
 '1602',
 '1606',
 '161',
 '162',
 '1623',
 '16248',
 '163',
 '1633',
 '164',
 '165',
 '165282',
 '168',
 '17',
 '170',
 '1700',
 '172',
 '173',
 '174',
 '1744',
 '175',
 '176',
 '1769',
 '178',
 '178164',
 '17ع',
 '17فبراير',
 '18',
 '180',
 '18000',
 '181',
 '182',
 '183',
 '184',
 '1846',
 '185',
 '18506',
 '1854',
 '186',
 '1866',
 '187',
 '1870',
 '1875',
 '1878',
 '188',
 '1882',
 '189',
 '1890',
 '1896',
 '19',
 '190',
 '1903',
 '1905',
 '19070',
 '1911',
 '1916',
 '192',
 '19216816255',
 '1922',
 '193',
 '1930',
 '19309',
 '1932',
 '1934',
 '1935',
 '194',
 '1940',
 '1941',
 '1942',
 '1944',
 '1946',
 '1947',
 '1948',
 '195',
 '1950',
 '1951',
 '1952',
 '19532',
 '1955',
 '1956',
 '1957',
 '196',
 '1960',
 '19611962',
 '1962',
 '19621963',
 '1963',
 '19631964',
 '1964',
 '1965',
 '1967',
 '1967وقالت',
 '1968',
 '1969',
 '197',
 '1970',
 '1971',
 '1972',
 '1973',
 '1974',
 '1975',
 '1976',
 '1977',
 '1978ولد',
 '19791',
 '198',
 '1980',
 '19801981',
 '1981',
 '1982',
 '1983',
 '19831984',
 '1984',
 '1985',
 '1986',
 '19861987',
 '1987',
 '19871988',
 '1988',
 '1989',
 '19891990',
 '199',
 '1990',
 '1991',
 '1992',
 '19921993',
 '1993',
 '19931994',
 '1994',
 '1995',
 '19951996',
 '1996',
 '1997',
 '1998',
 '1999',
 '19فبراير',
 '1أوميج',
 '1ابدأ',
 '1ر798',
 '1صفر',
 '1كأس',
 '1مج',
 '1وحتى',
 '20',
 '200',
 '2000',
 '200000',
 '2000وتوج',
 '2001',
 '20012002',
 '20014',
 '2002',
 '20022003',
 '2003',
 '20032004',
 '2004',
 '20042005',
 '2005',
 '20052006',
 '20052015',
 '2006',
 '20062007',
 '2007',
 '20072008',
 '2008',
 '20082009',
 '20082013',
 '2009',
 '20092010',
 '20092019',
 '2009م',
 '2009وجاء',
 '201',
 '2010',
 '20102011',
 '20106',
 '2010واستقر',
 '2011',
 '20112012',
 '20112012وحقق',
 '2012',
 '20122013',
 '2012وجاءت',
 '2013',
 '20132014',
 '20132014وافتتح',
 '2013وذكرت',
 '2014',
 '201420105',
 '20142015',
 '20142015وقدم',
 '2014م',
 '2014وأوضح',
 '2015',
 '20152016',
 '20152019',
 '2015وأكدت',
 '2016',
 '20162017',
 '20162017وعند',
 '2016فقد',
 '2016وانخفض',
 '2016وبالنظر',
 '2016وفشل',
 '2016وقالت',
 '2017',
 '20172018',
 '2017وبحسب',
 '2017وقال',
 '2017وكتبت',
 '2018',
 '20182019',
 '20182019الأهلي',
 '20182019الزمالك',
 '20182019وظهر',
 '2018ف',
 '2018وجاء',
 '2018وسجل',
 '2018وقال',
 '2018وقالت',
 '2019',
 '20192020',
 '2019وتعتبر',
 '2019ويتك',
 '2019ويجد',
 '2019ويعا',
 '2019وينتظر',
 '2019يمتلك',
 '202',
 '2020',
 '20202021ومنذ',
 '2020أحرز',
 '2020استبعد',
 '2020وأكد',
 '2020وأوضحت',
 '2020وجاء',
 '2020وقام',
 '2020ووفقا',
 '2021',
 '20212022',
 '2021وقال',
 '2022',
 '2023',
 '2023وتقضي',
 '2024',
 '2025',
 '2025وانضم',
 '2026',
 '2029',
 '203',
 '2030',
 '2030واضاف',
 '2035',
 '2035وأضاف',
 '2036',
 '204',
 '2040',
 '2042',
 '2050',
 '2051',
 '2055',
 '2060',
 '20705',
 '2071',
 '208',
 '20المستخدم',
 '20ودخل',
 '21',
 '210',
 '2100',
 '211',
 '2117',
 '212',
 '213',
 '214',
 '2145',
 '2148',
 '21601080',
 '21781',
 '2182',
 '21المستخدم',
 '21وأثارت',
 '21وجاء',
 '21ودخل',
 '22',
 '220',
 '2200',
 '2208',
 '221',
 '222',
 '22201080',
 '223',
 '2232',
 '225',
 '226',
 '227',
 '2274',
 '228',
 '22سجل',
 '23',
 '230',
 '2300',
 '231',
 '232',
 '233',
 '234',
 '235',
 '236',
 '237',
 '238',
 '24',
 '240',
 '24000',
 '240ملجم',
 '241',
 '243',
 '2436',
 '245',
 '246',
 '247',
 '248',
 '2483',
 '2494',
 '24ساع',
 '25',
 '250',
 '2500',
 '2509',
 '25155',
 '252',
 '253',
 '254',
 '2545',
 '255',
 '256',
 '258',
 '259',
 '26',
 '260',
 '2622',
 '264',
 '265',
 '266',
 '27',
 '270',
 '2700',
 '27000',
 '2716',
 '273',
 '274',
 '276',
 '2772',
 '2778',
 '28',
 '280',
 '2800',
 '28000',
 '282',
 '283',
 '2850',
 '289',
 '29',
 '290',
 '2900',
 '295',
 '2950',
 '296',
 '2960',
 '2دراس',
 '2صفر',
 '2ـ',
 '30',
 '300',
 '3000',
 '30000',
 '302',
 '303',
 '304',
 '305',
 '306',
 '30الفوز',
 '31',
 '310',
 '311500',
 '312',
 '314',
 '315',
 '3168',
 '31ورفع',
 '31ولعب',
 '32',
 '320',
 '3200',
 '324',
 '325',
 '3250',
 '3266',
 '329',
 '33',
 '3300',
 '3319',
 '3348',
 '34',
 '340',
 '3400',
 '341',
 '3436',
 '345',
 '346',
 '3464',
 '347',
 '348',
 '35',
 '350',
 '3500',
 '352',
 '354',
 '357',
 '359',
 '36',
 '360',
 '3600',
 '364',
 '365',
 '367',
 '36وقال',
 '37',
 '370',
 '375',
 '377',
 '38',
 '3800',
 '385',
 '386',
 '387',
 '388',
 '389166',
 '39',
 '390',
 '391',
 '394',
 '395',
 '398',
 '3ر5',
 '3صفر',
 '3ـ',
 '3ـ1',
 '40',
 '400',
 '4000',
 '40000',
 '40وتعمل',
 '41',
 '413',
 '414',
 '4141',
 '417',
 '41735',
 '418',
 '419',
 '42',
 '420',
 '4200',
 '422',
 '4231',
 '425',
 '429000',
 '42وتألق',
 '42وحافظ',
 '43',
 '4312',
 '4321',
 '433',
 '4371',
 '438',
 '43وأنتهى',
 '44',
 '440000',
 '441',
 '442',
 '443',
 '447',
 '44750',
 '45',
 '450',
 '4500',
 '451',
 '453',
 '455',
 '456',
 '46',
 '460',
 '46000',
 '4608',
 '462',
 '464',
 '466',
 '467',
 '469',
 '47',
 '477',
 '48',
 '480',
 '484',
 '49',
 '490000',
 '499',
 '4999',
 '4صفر',
 '4ـ',
 '4فقد',
 '4وسجل',
 '50',
 '500',
 '5000',
 '50000',
 '505',
 '507',
 '51',
 '511',
 '512',
 '514',
 '516',
 '518',
 '52',
 '520',
 '522',
 '524',
 '525',
 '529',
 '53',
 '530',
 '5300',
 '53300000',
 '54',
 '540',
 '5400',
 '547',
 '548',
 '55',
 '550',
 '5500',
 '551',
 '554',
 '556',
 '559',
 '56',
 '56000',
 '5639وتوضح',
 '564',
 '57',
 '570',
 '573',
 '574',
 '5753',
 '5759',
 '578',
 '58',
 '58000',
 '583',
 '585',
 '5897',
 '59',
 '590',
 '5942',
 '5ر1',
 '5ر39',
 '5صفر',
 '60',
 '600',
 '6000',
 '604',
 '60م',
 '61',
 '611',
 '612',
 '615',
 '62',
 '6213',
 '622019',
 '623',
 '625326',
 '628',
 '63',
 '630',
 '63000',
 '637',
 '64',
 '640',
 '641',
 '642',
 '65',
 '650',
 '6500',
 '6544',
 '656',
 '66',
 '664',
 '669',
 '67',
 '671',
 '68',
 '68بهذ',
 '69',
 '692',
 '6959',
 '696',
 '6أسباب',
 '6ونص',
 '70',
 '700',
 '7000',
 '700000',
 '702',
 '708',
 '71',
 '711',
 '71999',
 '72',
 '720',
 '7288',
 '73',
 '732',
 '733',
 '74',
 '74044',
 '7466',
 '75',
 '750',
 '7500',
 '75230',
 '753',
 '76',
 '77',
 '776',
 '777091436',
 '78',
 '78000',
 '79',
 '793',
 '794',
 '795',
 '79وتتواجه',
 '7من',
 '80',
 '800',
 '80130',
 '804',
 '806',
 '81',
 '811',
 '812',
 '8150',
 '819',
 '82',
 '821',
 '82341',
 '825',
 '8295',
 '83',
 '830',
 '833',
 '834',
 '8385',
 '84',
 '840',
 '841',
 '845',
 '85',
 '850',
 '855',
 '856871477',
 '86',
 '860',
 '862',
 '865',
 '87',
 '8753',
 '876',
 '88',
 '880',
 '881',
 '89',
 '890',
 '899',
 '8ونجح',
 '90',
 '900000',
 '90140',
 '9090',
 '91',
 '911',
 '916',
 '917',
 '918',
 '9192',
 '92',
 '922019',
 '922019وكتب',
 '9293',
 '92وبهذ',
 '93',
 '9382',
 '939',
 '94',
 '940',
 '945',
 '95',
 '957',
 '95805',
 '96',
 '960',
 '9691',
 '97',
 '974',
 '98',
 '9800',
 '99',
 '9938',
 '999',
 '9وجاء',
 'ءوكتب',
 'آبء',
 'آثر',
 'آخر',
 'آدء',
 'آرء',
 'آرئ',
 'آرثر',
 'آسس',
 'آكل',
 'آلف',
 'آلم',
 'آمر',
 'آمل',
 'آنهو',
 'آيباد',
 'آيفون7',
 'أؤكد',
 'أئل',
 'أبتسم',
 'أبحاث',
 'أبد',
 'أبدى',
 'أبرز',
 'أبريل',
 'أبسط',
 'أبض',
 'أبطأ',
 'أبطاء',
 'أبطال',
 'أبعاد',
 'أبعد',
 'أبل',
 'أبلغ',
 'أبناء',
 'أبهر',
 'أبو',
 'أبوظب',
 'أبوظبى',
 'أبى',
 'أبيدال',
 'أبيدوس',
 'أتبع',
 'أتج',
 'أتح',
 'أتحدث',
 'أتخصص',
 'أتخلى',
 'أتذكر',
 'أتطلع',
 'أتعرض',
 'أتعلم',
 'أتقاضى',
 'أتقبل',
 'أتقدم',
 'أتل',
 'أتم',
 'أتمنى',
 'أتوبيس',
 'أتى',
 'أثب',
 'أثر',
 'أثرى',
 'أثق',
 'أثناء',
 'أثنى',
 'أثيوب',
 'أجب',
 'أجتهد',
 'أجج',
 'أجر',
 'أجرى',
 'أجزاء',
 'أجساد',
 'أجل',
 'أجنح',
 'أجند',
 'أجهز',
 'أجويرو',
 'أجى',
 'أجيال',
 'أجيرى',
 'أجيى',
 'أحباب',
 'أحترم',
 'أحجام',
 'أحد',
 'أحداث',
 'أحداد',
 'أحدث',
 'أحذ',
 'أحرز',
 'أحرف',
 'أحض',
 'أحضر',
 'أحظى',
 'أحق',
 ...]

### 1972 records with 14785 words (features)

In [14]:
len(x[0])

14785

## NearestNeighbors algorithm is not KNN, its an unsupervised learning algorithm takes x_features only and trying to find the y label

## the y_label here is clustering the articles that have the same content
`Neighbors` --> Number of neighbors required for each sample 
in our case 

`Neighbors` tells us how many article do you want to return

by giving the x into the algorithm after the fitting process, it starts to gives the recommendations( the closest Neighbors) for each article

In [27]:
from sklearn.neighbors import NearestNeighbors

n=5

nbrs = NearestNeighbors(n_neighbors=n+1)

nbrs.fit(x)

distances, indices = nbrs.kneighbors(x)

indices

array([[   0,  190,  312,  804,  153,  518],
       [   1,    5,  220,  188,  600,  805],
       [   2,  140,  946,  317,  150,  351],
       ...,
       [1969, 1894, 1793, 1830, 1874, 1140],
       [1970, 1830, 1894, 1831, 1793,  384],
       [1971, 1841, 1085, 1185, 1257, 1195]], dtype=int64)

## Observations:- each row in the indices represents an article 
### in the first row, [0,190,312,804,153,518]--> tells you the indices of the articles that recommended for article 0 ( article with index 0--> the first article)

## Observations:- ofcourse the first record in first row tells you the article number 0 ( or the first article ) recommended it self make sense, therefore you will find `always` the distance =0

In [55]:
indices

array([[   0,  190,  312,  804,  153,  518],
       [   1,    5,  220,  188,  600,  805],
       [   2,  140,  946,  317,  150,  351],
       ...,
       [1969, 1894, 1793, 1830, 1874, 1140],
       [1970, 1830, 1894, 1831, 1793,  384],
       [1971, 1841, 1085, 1185, 1257, 1195]], dtype=int64)

In [16]:
distances

array([[ 0.        , 10.48808848, 10.90871211, 12.        , 12.12435565],
       [ 0.        , 14.93318452, 15.90597372, 17.        , 17.17556404],
       [ 0.        , 15.5241747 , 17.02938637, 17.05872211, 17.4642492 ],
       ...,
       [ 0.        , 26.70205985, 27.83882181, 27.91057147, 29.22327839],
       [ 0.        , 31.36877428, 31.74901573, 31.93743885, 32.52691193],
       [ 0.        , 23.47338919, 23.97915762, 24.22808288, 24.24871131]])

### lets visualize the content

In [28]:
df.iloc[[   0,  190,  312,  804,  153]]

,url,title,image,creator,keywords,description,article,label,text,clean_text
0,https://www.almasryalyoum.com/news/details/137...,لاسارتي يعلن تشكيل الأهلي لمباراة الساورة | ال...,https://mediaaws.almasryalyoum.com/news/veryla...,أحمد مجدي رجب,"الأهلي, لاسارتي, شبيبة الساورة, الجزائر, دوري ...",أعلن المدير الفني الأورجوياني مارتن لاسارتي ال...,أعلن المدير الفني الأورجوياني مارتن لاسارتي ال...,8.0,لاسارتي يعلن تشكيل الأهلي لمباراة الساورة | ال...,اسر يعل شكل اهل بار سار صري اليوم حمد جدي رجب ...
192,https://www.almasryalyoum.com/news/details/137...,«لاسارتي» يعلن تشكيل الأهلي لمباراة فيتا كلوب ...,https://mediaaws.almasryalyoum.com/news/veryla...,أحمد حمدي,"الأهلي, فيتا كلوب, دوري أبطال أفريقيا, مباراة ...",أعلن مارتن لاسارتي، المدير الفني للنادي الأهلي...,أعلن مارتن لاسارتي، المدير الفني للنادي الأهلي...,8.0,«لاسارتي» يعلن تشكيل الأهلي لمباراة فيتا كلوب ...,اسر يعل شكل اهل بار فيت كلب صري اليوم حمد حمد ...
317,https://www.almasryalyoum.com/news/details/137...,لاسارتي يعلن تشكيل الأهلي لمواجهة بتروجت | الم...,https://mediaaws.almasryalyoum.com/news/veryla...,عمرو الصاوي,"لاسارتي, الأهلي, بتروجت",أعلن مارتن لاسارتي، المدير الفني للفريق الأول ...,أعلن مارتن لاسارتي، المدير الفني للفريق الأول ...,8.0,لاسارتي يعلن تشكيل الأهلي لمواجهة بتروجت | الم...,اسر يعل شكل اهل واج ترج صري اليوم عمرو صوي اسر...
816,https://www.almasryalyoum.com/news/details/137...,«لاسارتي» يعلن تشكيل الأهلي لمواجهة «الإنتاج» ...,https://mediaaws.almasryalyoum.com/news/veryla...,أحمد مجدي رجب,"الأهلي, أخبار الرياضة, الإنتاج الحربي, الدوري ...",مارتن لاسارتي، المدير الفني للنادي الأهلي أعلن...,مارتن لاسارتي، المدير الفني للنادي الأهلي أعلن...,8.0,«لاسارتي» يعلن تشكيل الأهلي لمواجهة «الإنتاج» ...,اسر يعل شكل اهل واج ناج صري اليوم حمد جدي رجب ...
155,https://www.almasryalyoum.com/news/details/137...,فتح «الحجز الإلكتروني» لتذاكر مباراة الأهلي و...,https://mediaaws.almasryalyoum.com/news/veryla...,عمرو الصاوي,"الأهلي, شبيبة الساورة, أخبار الرياضة",أعلنت لجنة المباريات بالنادي الأهلي عن فتح الح...,أعلنت لجنة المباريات بالنادي الأهلي عن فتح الح...,8.0,فتح «الحجز الإلكتروني» لتذاكر مباراة الأهلي و...,فتح حجز كترو ذكر برا اهل شبب سار صري اليوم عمر...

In [31]:
rec = pd.DataFrame(indices,columns=['url','rec1','rec2','rec3','rec4','rec5'])
rec.head()

   url  rec1  rec2  rec3  rec4  rec5
0    0   190   312   804   153   518
1    1     5   220   188   600   805
2    2   140   946   317   150   351
3    3    22    21    12   674   185
4    4   150   477   522   470   518

In [57]:
df.iloc[190].url

'https://www.almasryalyoum.com/news/details/1376714'

In [32]:
df.iloc[190].url

'https://www.almasryalyoum.com/news/details/1376714'

In [35]:
df.iloc[190]

url            https://www.almasryalyoum.com/news/details/137...
title          «لاسارتي» يعلن تشكيل الأهلي لمباراة فيتا كلوب ...
image          https://mediaaws.almasryalyoum.com/news/veryla...
creator                                                أحمد حمدي
keywords       الأهلي, فيتا كلوب, دوري أبطال أفريقيا, مباراة ...
description    أعلن مارتن لاسارتي، المدير الفني للنادي الأهلي...
article        أعلن مارتن لاسارتي، المدير الفني للنادي الأهلي...
label                                                          8
text           «لاسارتي» يعلن تشكيل الأهلي لمباراة فيتا كلوب ...
clean_text     اسر يعل شكل اهل بار فيت كلب صري اليوم حمد حمد ...
Name: 192, dtype: object

## i want the url only

In [36]:
df.iloc[190].url

'https://www.almasryalyoum.com/news/details/1376714'

In [37]:
def replace_i_url(i):
    return df.iloc[i].url

In [38]:
replace_i_url(0)

'https://www.almasryalyoum.com/news/details/1378798'

In [39]:
rec

       url  rec1  rec2  rec3  rec4  rec5
0        0   190   312   804   153   518
1        1     5   220   188   600   805
2        2   140   946   317   150   351
3        3    22    21    12   674   185
4        4   150   477   522   470   518
...    ...   ...   ...   ...   ...   ...
1967  1967  1388  1371  1405  1043  1100
1968  1968  1969  1896  1894  1830  1797
1969  1969  1894  1793  1830  1874  1140
1970  1970  1830  1894  1831  1793   384
1971  1971  1841  1085  1185  1257  1195

[1972 rows x 6 columns]

### dataframe.apply --> can be used on only one column
### dataframe.applymap ---> can be used on more than one column ---> all dataframe

In [40]:
rec = rec.applymap(replace_i_url)
rec.head()

,url,rec1,rec2,rec3,rec4,rec5
0,https://www.almasryalyoum.com/news/details/137...,https://www.almasryalyoum.com/news/details/137...,https://www.almasryalyoum.com/news/details/137...,https://www.almasryalyoum.com/news/details/137...,https://www.almasryalyoum.com/news/details/137...,https://www.almasryalyoum.com/news/details/137...
1,https://www.almasryalyoum.com/news/details/137...,https://www.almasryalyoum.com/news/details/137...,https://www.almasryalyoum.com/news/details/137...,https://www.almasryalyoum.com/news/details/137...,https://www.almasryalyoum.com/news/details/137...,https://www.almasryalyoum.com/news/details/137...
2,https://www.almasryalyoum.com/news/details/137...,https://www.almasryalyoum.com/news/details/137...,https://www.almasryalyoum.com/news/details/136...,https://www.almasryalyoum.com/news/details/137...,https://www.almasryalyoum.com/news/details/137...,https://www.almasryalyoum.com/news/details/137...
3,https://www.almasryalyoum.com/news/details/137...,https://www.almasryalyoum.com/news/details/137...,https://www.almasryalyoum.com/news/details/137...,https://www.almasryalyoum.com/news/details/137...,https://www.almasryalyoum.com/news/details/137...,https://www.almasryalyoum.com/news/details/137...
4,https://www.almasryalyoum.com/news/details/137...,https://www.almasryalyoum.com/news/details/137...,https://www.almasryalyoum.com/news/details/137...,https://www.almasryalyoum.com/news/details/137...,https://www.almasryalyoum.com/news/details/137...,https://www.almasryalyoum.com/news/details/137...

### now lets say we want to recommend to the article 0

In [41]:
replace_i_url(0)

'https://www.almasryalyoum.com/news/details/1378798'

In [43]:
rec[rec.url=='https://www.almasryalyoum.com/news/details/1378798']

,url,rec1,rec2,rec3,rec4,rec5
0,https://www.almasryalyoum.com/news/details/137...,https://www.almasryalyoum.com/news/details/137...,https://www.almasryalyoum.com/news/details/137...,https://www.almasryalyoum.com/news/details/137...,https://www.almasryalyoum.com/news/details/137...,https://www.almasryalyoum.com/news/details/137...

In [44]:
rec[rec.url=='https://www.almasryalyoum.com/news/details/1378798'].values

array([['https://www.almasryalyoum.com/news/details/1378798',
        'https://www.almasryalyoum.com/news/details/1376714',
        'https://www.almasryalyoum.com/news/details/1375311',
        'https://www.almasryalyoum.com/news/details/1370685',
        'https://www.almasryalyoum.com/news/details/1377073',
        'https://www.almasryalyoum.com/news/details/1373378']],
      dtype=object)

In [45]:
rec[rec.url=='https://www.almasryalyoum.com/news/details/1378798'].values[0]

array(['https://www.almasryalyoum.com/news/details/1378798',
       'https://www.almasryalyoum.com/news/details/1376714',
       'https://www.almasryalyoum.com/news/details/1375311',
       'https://www.almasryalyoum.com/news/details/1370685',
       'https://www.almasryalyoum.com/news/details/1377073',
       'https://www.almasryalyoum.com/news/details/1373378'], dtype=object)

In [46]:
rec[rec.url=='https://www.almasryalyoum.com/news/details/1378798'].values[0][1:]

array(['https://www.almasryalyoum.com/news/details/1376714',
       'https://www.almasryalyoum.com/news/details/1375311',
       'https://www.almasryalyoum.com/news/details/1370685',
       'https://www.almasryalyoum.com/news/details/1377073',
       'https://www.almasryalyoum.com/news/details/1373378'], dtype=object)

## Content-Based in only one function

In [47]:
import re
from sklearn.feature_extraction.text import CountVectorizer
from nltk.stem import ISRIStemmer
from sklearn.neighbors import NearestNeighbors

In [48]:
cv = CountVectorizer()
ps = ISRIStemmer()   ## arabic
#sw = open('sw.txt','r').read().split('\n')   ## arabic

def clean(text):
    text = str(text)
    text = re.sub('[^ء-ي0-9 ]+','',text).strip()  ## arabic
    filtered_words = []
    for word in text.split():   ## arabic 
        #if word not in sw:
        filtered_words.append(ps.stem(word))
    return ' '.join(filtered_words)

def train(n=5):
    df = pd.read_csv('articles.csv')
    df = df[['url', 'title', 'creator', 'keywords','article']]
    df.dropna(inplace=True)
    df['text'] = df.title+" "+df.creator+" "+df.keywords+" "+df.article
    df['clean_text'] = df.text.apply(clean)
    x  = cv.fit_transform(df.clean_text).toarray()
    nbrs = NearestNeighbors(n_neighbors=n+1)
    nbrs.fit(x)
    distances, indices = nbrs.kneighbors(x)
    columns = []
    for i in range(1,n+1):
        columns.append('rec'+str(i))
    columns.insert(0,'url')
    rec = pd.DataFrame(indices,columns=columns)
    rec = rec.applymap(lambda x: df.iloc[x].url)
    return rec

def predict(url):
    return rec[rec.url==url].values[0][1:]

In [49]:
rec = train(10)

In [50]:
rec.url[0]

'https://www.almasryalyoum.com/news/details/1378798'

In [51]:
predict(rec.url[0])

array(['https://www.almasryalyoum.com/news/details/1376714',
       'https://www.almasryalyoum.com/news/details/1375311',
       'https://www.almasryalyoum.com/news/details/1370685',
       'https://www.almasryalyoum.com/news/details/1377073',
       'https://www.almasryalyoum.com/news/details/1376529',
       'https://www.almasryalyoum.com/news/details/1373378',
       'https://www.almasryalyoum.com/news/details/1369474',
       'https://www.almasryalyoum.com/news/details/1371746',
       'https://www.almasryalyoum.com/news/details/1377255',
       'https://www.almasryalyoum.com/news/details/1371831'], dtype=object)